# Generated by Django 5.0 on 2025-04-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upswap_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequest',
            name='initial_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
