# Generated by Django 5.0 on 2025-04-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upswap_chat', '0003_chatrequest_is_clicked'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequest',
            name='is_undo',
            field=models.BooleanField(default=False, help_text='True if user wants to undo the action'),
        ),
    ]
