# Generated by Django 5.0 on 2025-04-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upswap_chat', '0004_chatrequest_is_undo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequest',
            name='is_rejected',
            field=models.BooleanField(default=False, help_text='True if the request is rejected'),
        ),
    ]
