# Generated by Django 5.0 on 2025-06-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upswap_chat', '0008_chatmessage_seen_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequest',
            name='participation_status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('ACCEPTED', 'accepted'), ('REJECTED', 'rejected')], default='PENDING'),
        ),
    ]
