# Generated by Django 5.0 on 2025-06-20 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_alter_activity_participants'),
        ('upswap_chat', '0009_chatrequest_participation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrequest',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_requests', to='main.activity'),
        ),
    ]
