# Generated by Django 5.0 on 2025-06-25 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upswap_chat', '0010_alter_chatrequest_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='chat_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_room', to='upswap_chat.chatrequest'),
        ),
    ]
