# Generated by Django 5.0 on 2025-05-09 20:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals_agent', '0001_initial'),
        #('main', '0090_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_trigger_point', models.CharField(choices=[('weather', 'Weather'), ('product_expiry', 'Product Expiry'), ('holiday_special', 'Holiday Special'), ('local_event', 'Local Event'), ('competitor_action', 'Competitor Action'), ('stock_level', 'Stock Level')], max_length=50)),
                ('event_details_text', models.TextField()),
                ('event_location_latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('event_location_longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('event_timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_for_suggestion', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.address')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.vendorkyc')),
            ],
        ),
    ]
