# Generated by Django 5.0 on 2025-06-05 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals_agent', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealsuggestion',
            name='is_implemented_as_deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.createdeal'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.address'),
        ),
        migrations.AddField(
            model_name='event',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.vendorkyc'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deals_agent.category'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vendorkyc'),
        ),
        migrations.AddField(
            model_name='dealsuggestion',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals_agent.inventoryitem'),
        ),
        migrations.AddField(
            model_name='itembatch',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals_agent.inventoryitem'),
        ),
        migrations.AddField(
            model_name='dealsuggestion',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deals_agent.itembatch'),
        ),
        migrations.AddField(
            model_name='itembatch',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deals_agent.supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('vendor', 'sku')},
        ),
        migrations.AlterUniqueTogether(
            name='itembatch',
            unique_together={('item', 'batch_number')},
        ),
    ]
