# Generated by Django 3.2.25 on 2024-08-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityimage',
            name='user_uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
