# Generated by Django 3.2.25 on 2024-08-29 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20)),
                ('retype_account_number', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=255)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('vendor_kyc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='main.vendorkyc')),
            ],
        ),
    ]
