# Generated by Django 3.2.25 on 2024-08-29 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bankdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesProvide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('chosen_item_category', models.CharField(choices=[('RESTAURANTS', 'Restaurants'), ('CONSULTANTS', 'Consultants'), ('ESTATE_AGENTS', 'Estate Agents'), ('RENT_HIRE', 'Rent & Hire'), ('DENTIST', 'Dentist'), ('PERSONAL_CARE', 'Personal Care'), ('FOOD', 'Food'), ('BAKERY', 'Bakery'), ('GROCERIES', 'Groceries'), ('OTHERS', 'Others')], default='OTHERS', max_length=20)),
                ('item_description', models.TextField()),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendor_kyc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_provide', to='main.vendorkyc')),
            ],
        ),
    ]
