# Generated by Django 5.0 on 2024-09-27 18:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_vendorkyc_latitude_alter_vendorkyc_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdeal',
            name='deal_post_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
