# Generated by Django 3.2.25 on 2024-08-21 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_chatrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
