# Generated by Django 3.2.25 on 2024-08-29 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_servicesprovide'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseBusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('vendor_kyc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='main.vendorkyc')),
            ],
        ),
    ]
