# Generated by Django 3.2.25 on 2024-09-11 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_createdeal_dealimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdeal',
            name='vendor_kyc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='main.vendorkyc'),
        ),
    ]
