# Generated by Django 5.0 on 2024-09-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_createdeal_deal_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdeal',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createdeal',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
