# Generated by Django 3.2.25 on 2024-08-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_choosebusinesshours'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorkyc',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_profile_pics/'),
        ),
    ]
