# Generated by Django 3.2.25 on 2024-08-05 08:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customuser_otp_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('activity_title', models.CharField(max_length=50)),
                ('activity_description', models.TextField()),
                ('activity_type', models.CharField(choices=[('TECH_GAMING', 'Tech and Gaming'), ('VOLUNTEER_OPPORTUNITIES', 'Volunteer Opportunities'), ('CULTURAL_EXCHANGES', 'Cultural Exchanges'), ('INTELLECTUAL_PURSUITS', 'Intellectual Pursuits'), ('SPORTS_RECREATION', 'Sports and Recreation'), ('ARTS_CRAFTS', 'Arts and Crafts'), ('SOCIAL_GATHERINGS', 'Social Gatherings'), ('EDUCATIONAL_WORKSHOPS', 'Educational Workshops'), ('MUSIC_ENTERTAINMENT', 'Music and Entertainment')], max_length=50)),
            ],
        ),
    ]
