# Generated by Django 5.0 on 2024-10-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_createdeal_end_date_createdeal_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdeal',
            name='deal_valid_till_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='createdeal',
            name='deal_valid_till_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
