# Generated by Django 3.2.25 on 2024-09-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_createdeal_vendor_kyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorkyc',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
