# Generated by Django 3.2.25 on 2024-08-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_vendorkyc_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choosebusinesshours',
            name='vendor_kyc',
        ),
        migrations.RemoveField(
            model_name='servicesprovide',
            name='vendor_kyc',
        ),
        migrations.AddField(
            model_name='vendorkyc',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vendorkyc',
            name='bank_name',
            field=models.CharField(blank=True, default='Unknown Bank', max_length=100),
        ),
        migrations.AddField(
            model_name='vendorkyc',
            name='business_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='vendorkyc',
            name='chosen_item_category',
            field=models.CharField(choices=[('RESTAURANTS', 'Restaurants'), ('CONSULTANTS', 'Consultants'), ('ESTATE_AGENTS', 'Estate Agents'), ('RENT_HIRE', 'Rent & Hire'), ('DENTIST', 'Dentist'), ('PERSONAL_CARE', 'Personal Care'), ('FOOD', 'Food'), ('BAKERY', 'Bakery'), ('GROCERIES', 'Groceries'), ('OTHERS', 'Others')], default='OTHERS', max_length=50),
        ),
        migrations.AddField(
            model_name='vendorkyc',
            name='ifsc_code',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AddField(
            model_name='vendorkyc',
            name='item_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vendorkyc',
            name='item_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vendorkyc',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vendorkyc',
            name='retype_bank_account_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='BankDetails',
        ),
        migrations.DeleteModel(
            name='ChooseBusinessHours',
        ),
        migrations.DeleteModel(
            name='ServicesProvide',
        ),
    ]
