# Generated by Django 3.2.25 on 2024-08-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='created_id',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('TECH_GAMING', 'Tech and Gaming'), ('VOLUNTEER_OPPORTUNITIES', 'Volunteer Opportunities'), ('CULTURAL_EXCHANGES', 'Cultural Exchanges'), ('INTELLECTUAL_PURSUITS', 'Intellectual Pursuits'), ('SPORTS_RECREATION', 'Sports and Recreation'), ('ARTS_CRAFTS', 'Arts and Crafts'), ('SOCIAL_GATHERINGS', 'Social Gatherings'), ('EDUCATIONAL_WORKSHOPS', 'Educational Workshops'), ('MUSIC_ENTERTAINMENT', 'Music and Entertainment'), ('OTHERS', 'Others')], max_length=50),
        ),
    ]
