# Generated by Django 5.0 on 2024-10-01 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_createdeal_deal_valid_till_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createdeal',
            old_name='deal_valid_till_end_time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='createdeal',
            old_name='deal_valid_till_start_time',
            new_name='start_time',
        ),
    ]
