# Generated by Django 3.2.25 on 2024-08-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20240830_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorkyc',
            name='business_hours',
            field=models.JSONField(default=dict),
        ),
    ]
