# Generated by Django 5.0 on 2024-10-01 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_deal_valid_till_end_time_createdeal_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealimage',
            name='image',
        ),
        migrations.AddField(
            model_name='dealimage',
            name='create_deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal_images', to='main.createdeal'),
        ),
        migrations.AddField(
            model_name='dealimage',
            name='images',
            field=models.ImageField(default=False, upload_to='deal_images/'),
        ),
        migrations.AlterField(
            model_name='createdeal',
            name='upload_images',
            field=models.TextField(blank=True, default=list, help_text='List of deals images paths'),
        ),
    ]
