# Generated by Django 5.0 on 2024-09-20 11:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_passwordresettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='expires_at',
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
