# Generated by Django 3.2.25 on 2024-08-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_vendorkyc_business_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorkyc',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendorkyc',
            name='chosen_item_category',
            field=models.CharField(blank=True, choices=[('Restaurants', 'Restaurants'), ('Consultants', 'Consultants'), ('Estate Agents', 'Estate Agents'), ('Rent & Hire', 'Rent & Hire'), ('Dentist', 'Dentist'), ('Personal Care', 'Personal Care'), ('Food', 'Food'), ('Bakery', 'Bakery'), ('Groceries', 'Groceries'), ('Others', 'Others')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendorkyc',
            name='ifsc_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorkyc',
            name='item_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
