# Generated by Django 5.0 on 2024-10-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_dealimage_image_dealimage_create_deal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdeal',
            name='upload_images',
            field=models.TextField(blank=True, default='[]', help_text='List of deals images paths'),
        ),
    ]
