# Generated by Django 5.0 on 2024-09-20 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_passwordresettoken_expires_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
