# Generated by Django 3.2.25 on 2024-08-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_activityimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='active_time',
            field=models.BooleanField(default=False),
        ),
    ]
