# Generated by Django 3.2.25 on 2024-08-06 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_activity_active_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='active_time',
            new_name='infinite_time',
        ),
    ]
