# Generated by Django 5.0 on 2024-10-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_createdeal_upload_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdeal',
            name='upload_images',
            field=models.TextField(blank=True, default='', help_text='List of deals images paths', max_length=255),
        ),
    ]
