# Generated by Django 3.2.25 on 2024-08-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_active_time_activity_infinite_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='infinite_time',
        ),
        migrations.AddField(
            model_name='activity',
            name='user_participation',
            field=models.BooleanField(default=True),
        ),
    ]
