# Generated by Django 3.2.25 on 2024-08-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20240830_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorkyc',
            name='business_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
