# Generated by Django 3.2.25 on 2024-08-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20240806_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='max_participation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
