# Generated by Django 5.0 on 2024-09-24 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_blacklistedaccesstoken_delete_blacklistedtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlacklistedAccessToken',
        ),
    ]
