# Generated by Django 3.2.25 on 2024-08-31 05:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_vendorkyc_business_hours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorkyc',
            options={},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='images',
        ),
        migrations.AlterField(
            model_name='vendorkyc',
            name='business_hours',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='vendorkyc',
            name='chosen_item_category',
            field=models.CharField(choices=[('Restaurants', 'Restaurants'), ('Consultants', 'Consultants'), ('Estate Agents', 'Estate Agents'), ('Rent & Hire', 'Rent Hire'), ('Dentist', 'Dentist'), ('Personal Care', 'Personal Care'), ('Food', 'Food'), ('Bakery', 'Bakery'), ('Groceries', 'Groceries'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vendorkyc',
            name='item_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vendorkyc',
            name='item_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vendorkyc',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='activity_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_images', to='main.activity')),
            ],
        ),
    ]
