# Generated by Django 3.2.25 on 2024-08-06 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_activity_max_participation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='max_participation',
        ),
    ]
