# Generated by Django 3.2.25 on 2024-08-31 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20240831_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='images',
            field=models.TextField(blank=True, help_text='Comma-separated paths to images'),
        ),
    ]
