# Generated by Django 3.2.25 on 2024-08-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_activity_max_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='max_participation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
