# Generated by Django 5.0 on 2024-10-03 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_location_latitude_createdeal_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdeal',
            name='vendor_kyc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='main.vendorkyc'),
        ),
    ]
