# Generated by Django 5.0 on 2024-10-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_createdeal_vendor_kyc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdeal',
            name='upload_images',
            field=models.TextField(blank=True, null=True),
        ),
    ]
