# Generated by Django 3.2.25 on 2024-08-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20240806_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='maximum_participations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='user_participation',
            field=models.BooleanField(default=True),
        ),
    ]
