# Generated by Django 5.0 on 2024-10-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_createdeal_upload_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorkyc',
            name='country_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='vendorkyc',
            name='dial_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
