# Generated by Django 3.2.25 on 2024-08-07 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20240806_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='maximum_participations',
            new_name='maximum_participants',
        ),
    ]
