# Generated by Django 3.2.25 on 2024-08-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_activity_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='images',
            field=models.TextField(blank=True, help_text='Comma-separated paths to images'),
        ),
    ]
