# Generated by Django 3.2.25 on 2024-08-07 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_maximum_participations_activity_maximum_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='maximum_participants',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='user_participation',
        ),
    ]
