# Generated by Django 5.0 on 2024-10-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_vendorkyc_country_code_vendorkyc_dial_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorkyc',
            name='chosen_item_category',
        ),
        migrations.RemoveField(
            model_name='vendorkyc',
            name='item_description',
        ),
        migrations.RemoveField(
            model_name='vendorkyc',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='vendorkyc',
            name='item_price',
        ),
        migrations.AddField(
            model_name='vendorkyc',
            name='services',
            field=models.JSONField(blank=True, default=list, help_text='List of services provided by the vendor'),
        ),
    ]
