# Generated by Django 3.2.25 on 2024-08-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20240807_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='maximum_participants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='user_participation',
            field=models.BooleanField(default=False),
        ),
    ]
