# Generated by Django 3.2.25 on 2024-08-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_activity_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorkyc',
            name='business_hours',
            field=models.TextField(default='{}', help_text='Business hours stored as JSON string.'),
        ),
    ]
