# Generated by Django 5.0 on 2024-10-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_vendorkyc_chosen_item_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorkyc',
            name='item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
