# Generated by Django 3.2.25 on 2024-08-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_vendorkyc_business_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorkyc',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
