# Generated by Django 3.2.25 on 2024-08-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20240807_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_infinite',
            field=models.BooleanField(default=True),
        ),
    ]
