# Generated by Django 5.0 on 2024-10-09 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_vendorkyc_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorkyc',
            name='item_name',
        ),
    ]
