# Generated by Django 5.0 on 2024-10-10 07:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_vendorkyc_city_remove_vendorkyc_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorkyc',
            name='business_hours',
        ),
        migrations.RemoveField(
            model_name='vendorkyc',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='vendorkyc',
            name='services',
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('item_name', models.CharField(max_length=255)),
                ('item_category', models.CharField(max_length=100)),
                ('item_description', models.TextField()),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('business_hours', models.JSONField(blank=True, default=dict, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('vendor_kyc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='main.vendorkyc')),
            ],
        ),
    ]
