# Generated by Django 3.2.25 on 2024-08-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20240808_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='infinite_time',
            field=models.BooleanField(default=False),
        ),
    ]
