# Generated by Django 3.2.25 on 2024-09-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20240906_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of the location', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.CharField(blank=True, help_text='Optional description of the location', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of the location', max_digits=9, null=True),
        ),
    ]
