# Generated by Django 5.0 on 2024-10-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_vendorkyc_business_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='business_hours',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='vendorkyc',
            name='business_hours',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='vendorkyc',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
