# Generated by Django 5.0 on 2024-10-10 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_service_business_hours_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_id',
            new_name='uuid',
        ),
    ]
