# Generated by Django 5.0 on 2024-10-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_rename_address_id_address_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorkyc',
            name='business_hours',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
