# Generated by Django 3.2.25 on 2024-09-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20240909_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='set_current_datetime',
            field=models.BooleanField(default=False),
        ),
    ]
