# Generated by Django 5.0 on 2024-10-10 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_vendorkyc_business_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorkyc',
            name='user',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
