# Generated by Django 3.2.25 on 2024-09-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_activity_set_current_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='infinite_time',
            field=models.BooleanField(default=True),
        ),
    ]
