# Generated by Django 5.0 on 2024-10-17 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_vendorkyc_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='id',
            new_name='uuid',
        ),
    ]
