# Generated by Django 5.0 on 2024-10-17 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_rename_id_customuser_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='uuid',
            new_name='id',
        ),
    ]
