# Generated by Django 3.2.25 on 2024-09-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_activity_infinite_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='user_participation',
            field=models.BooleanField(default=True),
        ),
    ]
