# Generated by Django 5.0 on 2024-10-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_createdeal_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeorder',
            name='payment_status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
