# Generated by Django 5.0 on 2024-10-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_placeorder_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeorder',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
