# Generated by Django 5.0 on 2024-11-06 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_activitycategory_servicecategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='item_category',
        ),
    ]
