# Generated by Django 5.0 on 2024-11-06 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_service_item_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitycategory',
            old_name='name',
            new_name='act_category',
        ),
    ]
