# Generated by Django 5.0 on 2024-11-06 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_rename_name_activitycategory_act_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitycategory',
            old_name='act_category',
            new_name='actv_category',
        ),
    ]
