# Generated by Django 5.0 on 2024-11-06 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_rename_act_category_activitycategory_actv_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicecategory',
            old_name='name',
            new_name='serv_category',
        ),
    ]
