# Generated by Django 5.0 on 2024-11-12 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_customuser_social_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='social_id',
        ),
    ]
