# Generated by Django 5.0 on 2024-11-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_remove_customuser_social_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityimage',
            name='image',
            field=models.ImageField(upload_to='activity_images/%(activity_id)s/'),
        ),
    ]
