# Generated by Django 5.0 on 2024-11-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_activityimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
