# Generated by Django 5.0 on 2024-11-18 12:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_activityimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealsImage',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('images', models.ImageField(upload_to='deal_images/<django.db.models.fields.UUIDField>/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('create_deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal_images', to='main.createdeal')),
            ],
        ),
        migrations.DeleteModel(
            name='DealImage',
        ),
    ]
