# Generated by Django 5.0 on 2024-11-18 17:27

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_dealsimage_delete_dealimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealsimage',
            name='images',
            field=models.ImageField(upload_to=main.models.deal_image_upload_path),
        ),
    ]
