# Generated by Django 5.0 on 2024-11-18 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_dealsimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealsimage',
            name='create_deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deals_assets', to='main.createdeal'),
        ),
    ]
