# Generated by Django 5.0 on 2024-11-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_dealsimage_create_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdeal',
            name='upload_images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
