# Generated by Django 5.0 on 2024-11-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_createdeal_upload_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealsimage',
            name='images',
            field=models.ImageField(upload_to='deal_images/'),
        ),
    ]
