# Generated by Django 5.0 on 2024-11-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_alter_dealsimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdeal',
            name='upload_images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
