# Generated by Django 5.0 on 2024-11-29 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_alter_createdeal_upload_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createdeal',
            old_name='upload_images',
            new_name='uploaded_images',
        ),
    ]
