# Generated by Django 5.0 on 2024-12-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_rename_upload_images_createdeal_uploaded_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
