# Generated by Django 5.0 on 2024-12-10 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_customuser_device_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DealsImage',
        ),
    ]
