# Generated by Django 5.0 on 2024-12-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_remove_vendorkyc_business_related_photos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='uploaded_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='ActivityImage',
        ),
    ]
