# Generated by Django 5.0 on 2024-12-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_remove_businessphoto_vendor_kyc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorkyc',
            name='upload_business_documents',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
