# Generated by Django 5.0 on 2024-12-12 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_alter_vendorkyc_upload_business_documents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorkyc',
            old_name='upload_business_documents',
            new_name='uploaded_business_documents',
        ),
    ]
