# Generated by Django 5.0 on 2024-12-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_rename_upload_business_documents_vendorkyc_uploaded_business_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorkyc',
            name='profile_pic',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
