# Generated by Django 5.0 on 2024-12-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_alter_vendorkyc_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorkyc',
            name='profile_pic',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
