# Generated by Django 5.0 on 2024-12-20 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_alter_vendorkyc_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='device_token',
        ),
    ]
