# Generated by Django 5.0 on 2024-12-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_customuser_bio_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
