# Generated by Django 5.0 on 2025-01-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='social_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
