# Generated by Django 5.0 on 2025-01-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_customuser_social_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(blank=True, choices=[('google', 'Google'), ('apple', 'Apple')], max_length=10, null=True),
        ),
    ]
