# Generated by Django 5.0 on 2025-02-06 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_customuser_type'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='PasswordResetOTP',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('otp', models.CharField(max_length=6)),
        #         ('used', models.BooleanField(default=False)),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        #     ],
        # ),
        migrations.CreateModel(
            name='FavoriteVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_vendors', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='main.vendorkyc')),
            ],
            options={
                'unique_together': {('user', 'vendor')},
            },
        ),
    ]
