# Generated by Django 5.0 on 2025-02-15 10:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_vendorrating_rating_id_passwordresetotp'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='PasswordResetOTP',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('otp', models.CharField(max_length=6)),
        #         ('used', models.BooleanField(default=False)),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        #     ],
        # ),
        migrations.CreateModel(
            name='RaiseAnIssueMyOrders',
            fields=[
                ('issue_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('describe_your_issue', models.TextField()),
                ('choose_files', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('place_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_issues', to='main.placeorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
