# Generated by Django 5.0 on 2025-02-16 18:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_passwordresetotp_raiseanissuevendors'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='PasswordResetOTP',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('otp', models.CharField(max_length=6)),
        #         ('used', models.BooleanField(default=False)),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        #     ],
        # ),
        migrations.CreateModel(
            name='RaiseAnIssueCustomUser',
            fields=[
                ('issue_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('describe_your_issue', models.TextField()),
                ('choose_files', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.activity')),
                ('against_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues_against', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues_raised', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
