# Generated by Django 5.0 on 2025-04-02 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_placeorder_placeorder_id_passwordresetotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatrequest',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='chatrequest',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='chatrequest',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='participants',
        ),
        # migrations.CreateModel(
        #     name='PasswordResetOTP',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('otp', models.CharField(max_length=6)),
        #         ('used', models.BooleanField(default=False)),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        #     ],
        # ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatRequest',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
                               