# Generated by Django 5.0 on 2025-04-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_device_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('deal', 'CreateDeal'), ('order_update', 'Order Update'), ('activity', 'Activity'), ('general', 'General')], max_length=50),
        ),
    ]
