# Generated by Django 5.0 on 2025-04-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_fcmdevice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FCMDevice',
        ),
    ]
