# Generated by Django 5.0 on 2025-06-12 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createdeal',
            name='select_service',
        ),
        migrations.AddField(
            model_name='createdeal',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='createdeal',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.service'),
        ),
    ]
