# Generated by Django 5.0 on 2025-06-12 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_remove_createdeal_select_service_createdeal_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createdeal',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='createdeal',
            name='start_now',
        ),
        migrations.RemoveField(
            model_name='createdeal',
            name='start_time',
        ),
    ]
