# Generated by Django 5.0 on 2025-06-12 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_alter_service_category'),
        ('main', '0094_remove_createdeal_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdeal',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.service'),
        ),
    ]
