# Generated by Django 5.0 on 2025-06-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0095_alter_createdeal_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='set_current_datetime',
            new_name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='activity_category',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='start_time',
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('Tech and Gaming', 'Tech and Gaming'), ('Volunteer Opportunities', 'Volunteer Opportunities'), ('Cultural Exchanges', 'Cultural Exchanges'), ('Intellectual Pursuits', 'Intellectual Pursuits'), ('Sports and Recreation', 'Sports and Recreation'), ('Arts and Crafts', 'Arts and Crafts'), ('Social Gatherings', 'Social Gatherings'), ('Educational Workshops', 'Educational Workshops'), ('Music and Entertainment', 'Music and Entertainment'), ('Others', 'Others')], default='Others', max_length=50),
            preserve_default=False,
        ),
    ]
