# Generated by Django 5.0 on 2025-06-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0101_favoriteservice_favoriteuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdeal',
            name='category',
            field=models.CharField(default='Others', max_length=100),
            preserve_default=False,
        ),
    ]
