# Generated by Django 5.0 on 2025-06-28 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0102_alter_createdeal_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.BigIntegerField()),
                ('location', models.JSONField(blank=True, default=dict, null=True)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deal_views', to='main.createdeal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
