# Generated by Django 5.0 on 2025-06-28 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0103_dealviewcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealviewcount',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_views', to='main.createdeal'),
        ),
    ]
