# Generated by Django 5.0 on 2025-06-30 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0104_alter_dealviewcount_deal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createdeal',
            name='view_count',
        ),
    ]
