# Generated by Django 5.0 on 2025-07-02 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0105_remove_createdeal_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection_code', models.JSONField(default=list)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('VENDOR_CANCEL', 'VENDOR_CANCEL'), ('USER_CANCEL', 'USER_CANCEL'), ('FULFILLED', 'FULFILLED')], default='PENDING')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.vendorkyc')),
            ],
        ),
    ]
