# Generated by Django 5.0 on 2025-07-02 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0106_buydeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='buydeal',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='buydeal',
            name='deal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.createdeal'),
        ),
    ]
