# Generated by Django 5.0 on 2025-07-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0107_buydeal_active_buydeal_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdeal',
            name='deals_left',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
