# Generated by Django 5.0 on 2025-07-02 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0108_createdeal_deals_left'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection_code', models.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('VENDOR_CANCEL', 'VENDOR_CANCEL'), ('USER_CANCEL', 'USER_CANCEL'), ('FULFILLED', 'FULFILLED')], default='PENDING')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.createdeal')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.vendorkyc')),
            ],
        ),
        migrations.DeleteModel(
            name='BuyDeal',
        ),
    ]
