# Generated by Django 5.0 on 2025-07-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_alter_service_category'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0109_purchase_delete_buydeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdeal',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_title',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='createdeal',
            name='deal_title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendorkyc',
            name='full_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activity_title'], name='main_activi_activit_8e33e4_idx'),
        ),
        migrations.AddIndex(
            model_name='createdeal',
            index=models.Index(fields=['deal_title'], name='main_create_deal_ti_9e8767_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['name'], name='main_custom_name_463909_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorkyc',
            index=models.Index(fields=['full_name'], name='main_vendor_full_na_90617f_idx'),
        ),
    ]
