# Generated by Django 5.0 on 2025-07-11 07:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0110_createdeal_is_deleted_alter_activity_activity_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToActivityRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(choices=[(Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=2)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'activity')},
            },
        ),
        migrations.CreateModel(
            name='UserToDealRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(choices=[(Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=2)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.createdeal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'deal')},
            },
        ),
        migrations.CreateModel(
            name='UserToVendorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(choices=[(Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=2)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vendorkyc')),
            ],
            options={
                'unique_together': {('user', 'vendor')},
            },
        ),
    ]
