# Generated by Django 5.0 on 2025-06-03 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0091_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('profile_photo', models.JSONField(blank=True, default=list)),
                ('title', models.CharField(max_length=100)),
                ('work_hours', models.JSONField(default=dict)),
                ('services', models.ManyToManyField(related_name='providers', to='main.service')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='main.vendorkyc')),
            ],
        ),
    ]
