# Generated by Django 5.0 on 2025-06-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('main', '0091_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='providers', to='main.service'),
        ),
    ]
