# Generated by Django 5.0 on 2025-06-04 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_servicecategory_alter_provider_vendor_service_and_more'),
        ('main', '0091_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='vendor',
            field=models.ForeignKey(default='87d25847-551b-495c-83ac-831f7dbe4801', on_delete=django.db.models.deletion.CASCADE, related_name='ven_service_categories', to='main.vendorkyc'),
            preserve_default=False,
        ),
    ]
