# Generated by Django 5.0 on 2025-06-06 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_rename_decription_service_description_appointment'),
        ('main', '0091_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='main.vendorkyc')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('vendor', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
