# Generated by Django 5.0 on 2025-06-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointment_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Automotive Services & Products', 'Automotive Services & Products'), ('Art, Crafts & Collectibles', 'Art, Crafts & Collectibles'), ('Baby Care', 'Baby Care'), ('Bakery', 'Bakery'), ('Books, Stationery & Toys', 'Books, Stationery & Toys'), ('Clothing', 'Clothing'), ('Clothing', 'Clothing'), ('Dentist', 'Dentist'), ('Electronics', 'Electronics'), ('Estate Agents', 'Estate Agents'), ('Fashion, Apparel & Accessories', 'Fashion, Apparel & Accessories'), ('Food', 'Food'), ('Furniture', 'Furniture'), ('Groceries', 'Groceries'), ('Health, Wellness & Fitness', 'Health, Wellness & Fitness'), ('Home, Living & Kitchen', 'Home, Living & Kitchen'), ('Others', 'Others'), ('Personal Care', 'Personal Care'), ('Pet Care Services & Supplies', 'Pet Care Services & Supplies'), ('Professional & Business Services', 'Professional & Business Services'), ('Rent & Hire', 'Rent & Hire'), ('Restaurants', 'Restaurants'), ('Sports & Outdoors', 'Sports & Outdoors'), ('Other Services & Consultations', 'Other Services & Consultations')], max_length=100),
        ),
    ]
