# Generated by Django 5.0 on 2025-07-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('expired', 'Expired'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('user_cancel', 'User_cancel'), ('vendor_cancel', 'Vendor_cancel')], default='pending', max_length=20),
        ),
    ]
