# Generated by Django 5.0 on 2025-07-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_slot',
            field=models.ManyToManyField(related_name='appointments', to='appointments.timeslot'),
        ),
    ]
