# Generated by Django 3.2.25 on 2024-09-11 18:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_vendorkyc_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='deal_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreateDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('deal_title', models.CharField(max_length=255)),
                ('deal_description', models.TextField()),
                ('select_service', models.CharField(blank=True, max_length=255)),
                ('upload_images', models.TextField(blank=True)),
                ('deal_valid_till_start_time', models.DateTimeField(blank=True, null=True)),
                ('deal_valid_till_end_time', models.DateTimeField(blank=True, null=True)),
                ('start_now', models.BooleanField(default=False)),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_deals', models.PositiveIntegerField()),
                ('location_house_no', models.CharField(blank=True, max_length=255)),
                ('location_road_name', models.CharField(blank=True, max_length=255)),
                ('location_country', models.CharField(blank=True, max_length=255)),
                ('location_state', models.CharField(blank=True, max_length=255)),
                ('location_city', models.CharField(blank=True, max_length=255)),
                ('location_pincode', models.CharField(blank=True, max_length=20)),
                ('vendor_kyc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='main.vendorkyc')),
            ],
        ),
    ]
