# Generated by Django 5.0 on 2025-06-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('sign_up', 'sign_up'), ('login', 'login'), ('logout', 'logout'), ('edit_profile', 'edit_profile'), ('place_order', 'place_order'), ('reset_password', 'reset_password'), ('verify_otp', 'verify_otp'), ('favorite_vendor', 'favorite_vendor'), ('unfavorite_vendor', 'unfavorite_vendor'), ('rate_vendor', 'rate_vendor'), ('raise_issue', 'raise_issue'), ('create_activity', 'create_activity'), ('deactivate_activity', 'deactivate_activity'), ('repost_activity', 'repost_activity'), ('show_interest_in_activity', 'show_interest_in_activity'), ('chat_request', 'chat_request'), ('accept_chat_req', 'accept_chat_req'), ('rejet_chat_req', 'rejet_chat_req'), ('apply_kyc', 'apply_kyc'), ('upload_deal', 'upload_deal'), ('end_deal', 'end_deal'), ('create_deal', 'create_deal'), ('edit_deal', 'edit_deal'), ('repost_deal', 'repost_deal'), ('deactivate_deal', 'deactivate_deal'), ('kyc_approved', 'kyc_approved'), ('notification_fired_for_event', 'notification_fired_for_event')], max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
