# Generated by Django 5.0 on 2025-04-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
